#!/bin/bash

#extract hop number,ip adresses andthe average of the 3 probes resposnse times, and seperate by line into csv format
prettify_traceroute(){

        output=$(traceroute -n $1)
        echo "$output" | while read line; do
        if [[ "$line" =~ ^[0-9]+ ]]; then
                hop=$(echo "$line" | awk '{print $1}')
                ips=($(echo "$line" | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}' | paste -sd ' '))
                times=($(echo "$line" | grep -oE '[0-9]+\.[0-9]+ ms' | awk '{print $1}'))


                sum=0
                count=0
                for t in "${times[@]}"; do
                        sum=$(echo "$sum + $t" | bc)
                        count=$((count + 1))
                done

                if [[ $count -gt 0 ]]; then
                        avg=$(echo "scale=3; $sum / $count" | bc)
                else
                        avg="-1"
                fi

                echo "$hop,$ips,$avg" >> task1Output.txt
        fi
        done
}

echo "Traceroute to Brazil:"
prettify_traceroute 200.160.4.6

echo ""
echo "Traceroute to Sweden:"
prettify_traceroute 80.76.149.102


echo ""
echo "Traceroute to New Zealand"
prettify_traceroute 23.236.62.147

#echo ""i
#echo "Traceroute to last"
#prettify_traceroute 23.236.62.147
 
